CREATE TABLE enrollments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    course_id BIGINT NOT NULL
);

CREATE INDEX idx_enrollments_course_id ON enrollments(course_id);
